### ISSUE TITLE
Importing into Akeneo feature

### ISSUE THREAD

**Issue by jgrossi** [synolia/Prestaneo#2]
Hi! 

First thanks for this amazing PS module :-)

I'm configuring a web store that uses Prestashop. There are a lot of products there so I'd like to know if there's some easy way to export from Prestashop and import the store products into the Akeneo software.

I tried to export the PS catalog (products) using the export button but the fields are a bit different from Akeneo. So I enabled the `Catalog in CSV format` PS module with some custom field names but it's exporting no products.

Do you know an easy way to export _from_ Prestashop and import the store products into Akeneo?

Thanks for the support. 

Best regards.

**Comment by Rmnndr** [comment]
Hi Junior,

First of all, sorry for our response time.
You maybe already have find a solution for your issue.

However, you try to match data between two specific softwares with their specific product import/export format. The best solution is probably the way you work by exporting data from Prestashop in order to rework the file to the Akeneo import standard file format.

I unfortunatly don't know out of box feture/addon to fit your needs.

Regards,

**Comment by jgrossi** [comment]
Hi @Rmnndr!

Thanks for the feedback. I'm still trying to find a solution for the problem, once my Akeneo installation is not importing even exporting.

But thanks for the feedback.

Regards,

**Comment by aistis-** [comment]
Hello,

I am working on the same case as @jgrossi 
We have an existing Prestashop (v1.5) and preparing data migration to Akeneo PIM (v1.6).
It is one time thing, later we would user Prestaneo for products sync (PIM->Prestashop).

@jgrossi Did you manage to find a solution to you case?
